[project]
name = "peeper-board-generator"
version = "1.2.3"
description = "An OJ Board Generator."
requires-python = ">=3.10"
dependencies = [
    "easy-pixie>=0.0.9",
    "lxml>=6.0.2",
    "pixie-python>=4.3.0",
    "python-dateutil>=2.9.0.post0",
    "requests>=2.32.5",
]
